version: 3.0.0.{build}-{branch}

branches:
  except:
    - gh-pages

install:
  - git submodule update --init --recursive

environment:
  matrix:
    - PRJ_GEN: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      BDIR: msvc2017
      PRJ_CFG: Release

build_script:
  - mkdir build.%BDIR%
  - cd build.%BDIR%
  - cmake .. -G "%PRJ_GEN%" "-DCMAKE_BUILD_TYPE=%PRJ_CFG%" %PARAMS%
  - cmake --build . --config "%PRJ_CFG%" --clean-first

test_script:
  - ctest -V --output-on-failure -C %PRJ_CFG%
